version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: df7j.a2
      POSTGRES_DB: taskflow
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d taskflow" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  app:
    image: eclipse-temurin:21-jdk
    container_name: java_app
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    command: ./mvnw spring-boot:run
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskflow?currentSchema=taskflow
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: df7j.a2
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:db/changelog/db.changelog-master.xml
      SPRING_LIQUIBASE_DEFAULT_SCHEMA: taskflow
    restart: unless-stopped

volumes:
  pgdata:
    driver: local